name: Node.js CI/CD

on:
  pull_request:
    branches: 
      - main  # Trigger only for pull requests targeting the "main" branch

jobs:
  # Test Application Job
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (latest LTS version)
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run tests to validate the application
      - name: Run Tests
        run: npm test

  # Deploy Application Job (only runs if the PR is merged)
  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: test  # Ensure this job runs only if the 'test' job passes
    if: github.event.pull_request.merged == true  # Only deploy if the PR is merged

    steps:
      # Step 1: Checkout the code again for the deployment job
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (same version as in the test job)
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 3: Install project dependencies (in case anything changed)
      - name: Install Dependencies
        run: npm install

      # Step 4: Create a deployment package (ZIP the app files)
      - name: Generate Deployment Package
        run: zip -r nodejs-app-build.zip .

      # Step 5: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-2'  # Specify the region here

      # Step 6: Deploy to AWS Elastic Beanstalk using the deployment package
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: 'node-js'
          environment_name: 'node-js-dev-env'
          version_label: ${{ github.sha }}
          region: 'eu-west-2'  # Ensure you specify the same region here
          deployment_package: nodejs-app-build.zip