name: Node.js CI/CD

on:
  push:
    branches: [ main ]   # Run on pushes to the "main" branch
  pull_request:
    branches: [ main ]   # Run on pull requests to the "main" branch

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Latest LTS version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: test  # Run only if the 'test' job passes
    if: github.event_name == 'push'  # Deploy only on push to main

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Generate Deployment Package
      - name: Generate Deployment Package
        run: zip -r nodejs-app-build.zip .

      # Step 5: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'node-js'
          environment_name: 'node-js-dev-env'
          version_label: ${{ github.sha }}
          region: eu-west-2
          deployment_package: nodejs-app-build.zip